# Generated by Django 5.0.1 on 2024-05-01 15:41

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Director',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, null=True)),
                ('designation', models.CharField(max_length=255, null=True)),
                ('pan', models.CharField(max_length=10, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Events',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Eventimage', models.FileField(null=True, upload_to='eventsimage/', verbose_name='')),
                ('NameofEvent', models.CharField(max_length=255)),
                ('Description', models.CharField(max_length=1000)),
                ('DateofEvent', models.DateField(null=True)),
                ('LinkforEvent', models.URLField(null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Form2',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('iande', models.FileField(null=True, upload_to='incomeandexpenditure/', verbose_name='')),
                ('incometaxtpan', models.FileField(null=True, upload_to='incometaxtpan/', verbose_name='')),
                ('FactoryRegistrationCertificate', models.FileField(null=True, upload_to='FactoryRegistrationCertificate/', verbose_name='')),
                ('MemorandumArticleofAssociation', models.FileField(null=True, upload_to='MemorandumArticleofAssociation/', verbose_name='')),
                ('GSTINRegistrationCopy', models.FileField(null=True, upload_to='GSTINRegistrationCopy/', verbose_name='')),
                ('IECodeCertificate', models.FileField(null=True, upload_to='IECodeCertificate/', verbose_name='')),
                ('ProfessionalCertificate', models.FileField(null=True, upload_to='ProfessionalCertificate/', verbose_name='')),
                ('CopyofLandDocument', models.FileField(null=True, upload_to='CopyofLandDocument/', verbose_name='')),
                ('LandHolding', models.FileField(null=True, upload_to='LandHolding/', verbose_name='')),
                ('passportsizephoto', models.FileField(null=True, upload_to='passportsizephoto/', verbose_name='')),
                ('DirectorsPartners', models.FileField(null=True, upload_to='DirectorsPartners/', verbose_name='')),
            ],
        ),
        migrations.CreateModel(
            name='Contact',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Name', models.CharField(max_length=255)),
                ('Email', models.EmailField(max_length=254)),
                ('phonenumber', models.BigIntegerField()),
                ('Description', models.CharField(max_length=1000)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Form1',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Nameofapplicant', models.CharField(max_length=255, null=True)),
                ('constitution', models.CharField(blank=True, choices=[('Individual', 'Individual'), ('Proprietory Firm', 'Proprietory Firm'), ('Partnership Firm', 'Partnership Firm'), ('LLP', 'LLP'), ('Private Limited', 'Private Limited'), ('Public Limited Unlisted', 'Public Limited Unlisted'), ('Public Limited Listed', 'Public Limited Listed'), ('Trust', 'Trust'), ('Society', 'Society'), ('Associations', 'Associations')], max_length=30, null=True)),
                ('individual_name', models.CharField(blank=True, help_text='Enter the name of the Individual', max_length=255, null=True)),
                ('is_individual', models.BooleanField(default=False, help_text='Check if the constitution is Individual')),
                ('Businessactivity', models.CharField(max_length=500, null=True)),
                ('regoffadd', models.CharField(max_length=500, null=True)),
                ('acoffice', models.CharField(max_length=500, null=True)),
                ('acwork', models.CharField(max_length=500, null=True)),
                ('cdlan', models.BigIntegerField(null=True)),
                ('cdphone', models.BigIntegerField(null=True)),
                ('cdemail', models.EmailField(max_length=254)),
                ('cdweb', models.URLField(blank=True, null=True)),
                ('aadhar', models.BigIntegerField(null=True)),
                ('pancardno', models.BigIntegerField(null=True)),
                ('GSTNo', models.BigIntegerField(null=True)),
                ('CompanyFirmRegNo', models.BigIntegerField(null=True)),
                ('SocietyAssociationRegNo', models.BigIntegerField(null=True)),
                ('paname', models.CharField(max_length=255, null=True)),
                ('papan', models.CharField(max_length=10, null=True)),
                ('paphone', models.CharField(max_length=15, null=True)),
                ('padesignation', models.CharField(max_length=255, null=True)),
                ('paaadhaar', models.CharField(max_length=12, null=True)),
                ('pamail_id', models.EmailField(max_length=254, null=True)),
                ('indmain_category', models.CharField(max_length=255, null=True)),
                ('indsub_category', models.CharField(max_length=255, null=True)),
                ('cmdomestic', models.CharField(max_length=255, null=True)),
                ('cmboth', models.CharField(max_length=255, null=True)),
                ('cmpercentage_of_imports', models.CharField(max_length=10, null=True)),
                ('cmglobal_market', models.CharField(max_length=255, null=True)),
                ('cmpercentage_of_exports', models.CharField(max_length=10, null=True)),
                ('country_name_foreign_collaboration', models.CharField(max_length=255, null=True)),
                ('collaborator_name_foreign_collaboration', models.CharField(max_length=255, null=True)),
                ('annual_turnover_year1', models.DecimalField(decimal_places=2, max_digits=15, null=True)),
                ('annual_turnover_year2', models.DecimalField(decimal_places=2, max_digits=15, null=True)),
                ('annual_turnover_year3', models.DecimalField(decimal_places=2, max_digits=15, null=True)),
                ('classindustry', models.CharField(choices=[('Large', 'Large'), ('Medium', 'Medium'), ('Small', 'Small'), ('Micro', 'Micro')], max_length=255, null=True)),
                ('direct_office_employees', models.BigIntegerField(null=True)),
                ('indirect_contractual_employees', models.BigIntegerField(null=True)),
                ('works_employees', models.BigIntegerField(null=True)),
                ('outsourced_employees', models.BigIntegerField(null=True)),
                ('esic', models.CharField(max_length=255, null=True)),
                ('epf', models.CharField(max_length=255, null=True)),
                ('branches_outside_india', models.CharField(max_length=500, null=True)),
                ('is_member_of_association', models.CharField(choices=[('Yes', 'Yes'), ('No', 'No')], default='No', max_length=3, null=True, verbose_name='Are you a member of any other Association')),
                ('association_name', models.CharField(blank=True, max_length=255, null=True, verbose_name='Association Name')),
                ('is_office_bearer', models.CharField(choices=[('Yes', 'Yes'), ('No', 'No')], default='No', max_length=3, null=True, verbose_name='Do you hold any Office Bearers position in any Association')),
                ('association_position', models.CharField(blank=True, max_length=255, null=True, verbose_name='Association Position')),
                ('reason_for_joining_chamber', models.TextField(null=True)),
                ('e_sign', models.FileField(null=True, upload_to='e_sign/', verbose_name='')),
                ('seal_image', models.FileField(null=True, upload_to='seal_image/', verbose_name='')),
                ('ror', models.TextField(blank=True, help_text='Reason of Rejection', null=True)),
                ('form_status', models.CharField(choices=[('pending', 'pending'), ('waiting for payment', 'waiting for payment'), ('payment done (approved)', 'payment done (approved)'), ('rejected', 'rejected')], default='pending', max_length=50)),
                ('directors', models.ManyToManyField(blank=True, related_name='form1s', to='chamber.director')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('Form2', models.ManyToManyField(blank=True, related_name='form2', to='chamber.form2')),
            ],
        ),
        migrations.CreateModel(
            name='PaymentTransaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('membership_type', models.CharField(choices=[('trader', 'Trader'), ('professional', 'Professional'), ('associations', 'Associations'), ('life', 'Life Membership')], max_length=20)),
                ('sales_turnover', models.CharField(blank=True, choices=[('upTo5Crore', 'Up to Rs. 5 Crore'), ('above5CroreUpTo10Crore', 'Above Rs. 5 Crore up to Rs. 10 Crore'), ('above10CroreUpTo25Crore', 'Above Rs. 10 Crore up to Rs. 25 Crore'), ('above25Crore', 'Above Rs. 25 Crore')], max_length=50, null=True)),
                ('card_number', models.CharField(max_length=20)),
                ('expiry_date', models.DateField()),
                ('cvv', models.CharField(max_length=4)),
                ('cardholder_name', models.CharField(max_length=255)),
                ('entrance_fee', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('selected_membership_amount', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('journal_subscription', models.BooleanField()),
                ('chamber_day_celebrations', models.BooleanField()),
                ('total_amount', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('registration_date', models.DateTimeField(default=django.utils.timezone.now)),
                ('membership_expiry_date', models.DateTimeField(blank=True, null=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
