# Generated by Django 5.0.3 on 2024-03-05 09:36

import phonenumber_field.modelfields
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Director',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('designation', models.CharField(max_length=255)),
                ('pan', models.CharField(max_length=10)),
            ],
        ),
        migrations.CreateModel(
            name='Form1',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Nameofapplicant', models.CharField(max_length=255)),
                ('constitution', models.CharField(blank=True, choices=[('Individual', 'Individual'), ('Proprietory Firm', 'Proprietory Firm'), ('Partnership Firm', 'Partnership Firm'), ('LLP', 'LLP'), ('Private Limited', 'Private Limited'), ('Public Limited Unlisted', 'Public Limited Unlisted'), ('Public Limited Listed', 'Public Limited Listed'), ('Trust', 'Trust'), ('Society', 'Society'), ('Associations', 'Associations')], max_length=30, null=True)),
                ('individual_name', models.CharField(blank=True, help_text='Enter the name of the Individual', max_length=255, null=True)),
                ('is_individual', models.BooleanField(default=False, help_text='Check if the constitution is Individual')),
                ('Businessactivity', models.CharField(max_length=500)),
                ('regoffadd', models.CharField(max_length=500)),
                ('acoffice', models.CharField(max_length=500)),
                ('acwork', models.CharField(max_length=500)),
                ('cdlan', phonenumber_field.modelfields.PhoneNumberField(max_length=128, region=None)),
                ('cdphone', phonenumber_field.modelfields.PhoneNumberField(max_length=128, region=None)),
                ('cdemail', models.EmailField(blank=True, max_length=254)),
                ('cdweb', models.URLField(blank=True, null=True)),
                ('aadhar', models.IntegerField()),
                ('pancardno', models.IntegerField()),
                ('GSTNo', models.IntegerField()),
                ('CompanyFirmRegNo', models.IntegerField()),
                ('SocietyAssociationRegNo', models.IntegerField()),
                ('paname', models.CharField(max_length=255)),
                ('papan', models.CharField(max_length=10)),
                ('paphone', models.CharField(max_length=15)),
                ('padesignation', models.CharField(max_length=255)),
                ('paaadhaar', models.CharField(max_length=12)),
                ('pamail_id', models.EmailField(max_length=254)),
                ('indmain_category', models.CharField(max_length=255)),
                ('indsub_category', models.CharField(max_length=255)),
                ('cmdomestic', models.CharField(max_length=255)),
                ('cmboth', models.CharField(max_length=255)),
                ('cmpercentage_of_imports', models.CharField(max_length=10)),
                ('cmglobal_market', models.CharField(max_length=255)),
                ('cmpercentage_of_exports', models.CharField(max_length=10)),
                ('country_name_foreign_collaboration', models.CharField(max_length=255)),
                ('collaborator_name_foreign_collaboration', models.CharField(max_length=255)),
                ('annual_turnover_year1', models.DecimalField(decimal_places=2, max_digits=15)),
                ('annual_turnover_year2', models.DecimalField(decimal_places=2, max_digits=15)),
                ('annual_turnover_year3', models.DecimalField(decimal_places=2, max_digits=15)),
                ('classindustry', models.CharField(choices=[('Large', 'Large'), ('Medium', 'Medium'), ('Small', 'Small'), ('Micro', 'Micro')], max_length=255)),
                ('direct_office_employees', models.IntegerField()),
                ('indirect_contractual_employees', models.IntegerField()),
                ('works_employees', models.IntegerField()),
                ('outsourced_employees', models.IntegerField()),
                ('esic', models.CharField(max_length=255)),
                ('epf', models.CharField(max_length=255)),
                ('branches_outside_india', models.CharField(max_length=500)),
                ('is_member_of_association', models.CharField(choices=[('Yes', 'Yes'), ('No', 'No')], default='No', max_length=3, verbose_name='Are you a member of any other Association')),
                ('association_name', models.CharField(blank=True, max_length=255, null=True, verbose_name='Association Name')),
                ('is_office_bearer', models.CharField(choices=[('Yes', 'Yes'), ('No', 'No')], default='No', max_length=3, verbose_name='Do you hold any Office Bearers position in any Association')),
                ('association_position', models.CharField(blank=True, max_length=255, null=True, verbose_name='Association Position')),
                ('reason_for_joining_chamber', models.TextField()),
                ('e_sign', models.ImageField(blank=True, null=True, upload_to='e_signs/')),
                ('seal_image', models.ImageField(blank=True, null=True, upload_to='seals/')),
                ('directors', models.ManyToManyField(blank=True, related_name='form1s', to='chamber.director')),
            ],
        ),
    ]
